version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - payment-service
      - inventory-service
      - shipping-service

  payment-service:
    build: ./payment-service
    ports:
      - "5001:5001"

  inventory-service:
    build: ./inventory-service
    ports:
      - "5002:5002"

  shipping-service:
    build: ./shipping-service
    ports:
      - "5003:5003"